FROM python:3.11

WORKDIR /app

COPY ./information_reader/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


COPY ./information_reader .
COPY ./shaerd /app/shaerd


CMD ["python", "-m", "reader_orchestrator"]